### ISSUE TITLE
Handle stack frames correctly

### ISSUE THREAD

**Issue by peace-maker** [theY4Kman/pysmx#6]
Currently when any function on the "callstack" returns it aborts the whole interpretion.
The following example will only print the following instead of looping properly and executing `func` again.

```
func
0
```

This is because the `call` handler just jumps to the target function's start_cip instead of starting a new interpreter loop.

Awesome library! 🎠 

```python
with open('test.smx', 'rb') as compiled:
	smx_code = SourcePawnPlugin(compiled)
	print(smx_code.runtime.call_function_by_name('OnPluginStart'))
```

```sourcepawn
public OnPluginStart()
{
  for (new i; i<5; i++)
    func();
  PrintToServer("start");
}

func()
{
  PrintToServer("func");
}
```

**Comment by theY4Kman** [comment]
Hey, I updated the library for Py3, and fixed this along the way. You still using this at all?

**Comment by peace-maker** [comment]
I wanted to use it to call special functions in obfuscated binaries, but haven't looked at it since then. I'll have a new go now that you're active again.
